2025-01-20 00:53:50,288 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\msaw.date.time.json
2025-01-20 00:53:50,292 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\prompts\prompts.yaml
2025-01-20 00:53:50,307 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\passwords\msaw.pw.json
2025-01-20 00:53:50,357 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\ux-design\msaw_ux_user_story_map.json
2025-01-20 00:53:50,376 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\msaw.german_steno_develop_dict.json
2025-01-20 00:53:50,380 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\msaw.common_phrases.json
2025-01-20 00:53:50,391 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\msaw.german_steno_dict.json
2025-01-20 00:53:50,403 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\msaw_practice_override.json
2025-01-20 00:53:50,406 - WARNING - dictionary `msaw\msaw.german_steno_dict.json` loaded with 1 invalid steno errors
2025-01-20 00:53:50,407 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\msaw.python.json
2025-01-20 00:53:50,522 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\csharp\msaw.css.blazor.json
2025-01-20 00:53:50,523 - WARNING - dictionary `msaw\msaw.python.json` loaded with 1 invalid steno errors
2025-01-20 00:53:50,525 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\commands\msaw.application.commands.json
2025-01-20 00:53:50,535 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\csharp\msaw.html.blazor.json
2025-01-20 00:53:50,538 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\commands\msaw.plover.commands.json
2025-01-20 00:53:50,540 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\msaw.test.modal
2025-01-20 00:53:50,555 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\pycharm\msaw.pycharm.commands.json
2025-01-20 00:53:50,576 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\numpad\msaw.numpad.json
2025-01-20 00:53:50,595 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\plugins\win\python39\site-packages\emily-modifiers-master\stuff\msaw_emily-modifiers.json
2025-01-20 00:53:50,614 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\plugins\win\python39\site-packages\emily-symbols-main\stuff\emily-symbols.json
2025-01-20 00:53:50,631 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\plugins\win\python39\site-packages\emily-modifiers-master\stuff\emily-modifiers.json
2025-01-20 00:53:50,700 - WARNING - dictionary `plugins\win\python39\site-packages\emily-modifiers-master\stuff\msaw_emily-modifiers.json` loaded with 15 invalid steno errors
2025-01-20 00:53:50,762 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\stnodvelop.json
2025-01-20 00:53:50,795 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\user.json
2025-01-20 00:53:50,842 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\main.json
2025-01-20 00:53:50,847 - WARNING - dictionary `stnodvelop.json` loaded with 2 invalid steno errors
2025-01-20 00:53:50,859 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\commands.json
2025-01-20 00:53:51,256 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\msaw.numpad.modal
2025-01-20 00:53:51,349 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\msaw.fingerspelling.modal
2025-01-20 00:53:51,398 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\msaw.fingerspelling_allcaps.modal
2025-01-20 00:53:51,427 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\commands\msaw_commands.json
2025-01-20 00:53:51,473 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\regenpfeifer_user_addition.json
2025-01-20 00:53:51,566 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\regenpfeifer_user.json
2025-01-20 00:53:51,612 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\regenpfeifer_main.json
2025-01-20 00:53:51,783 - INFO - loading dictionary: c:\users\msaw\appdata\local\plover\plover\msaw\suppress_untranslates.py
2025-01-20 00:53:54,406 - WARNING - dictionary `regenpfeifer_main.json` loaded with 6 invalid steno errors
2025-01-20 00:53:54,480 - INFO - loaded 33 dictionaries in 4.198s
2025-01-20 00:53:54,483 - ERROR - loading dictionary `msaw\msaw.test.modal` failed: [WinError 2] Das System kann die angegebene Datei nicht finden: './test.py'
2025-01-20 00:53:56,626 - INFO - Stroke(Z-Z : ['Z-', '-Z'])
2025-01-20 00:53:56,627 - ERROR - Error in lookup function: 
2025-01-20 00:53:56,628 - ERROR - engine on_stroked failed
Traceback (most recent call last):
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 147, in run
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 382, in _on_stroked
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 205, in translate
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 261, in flush
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 266, in _output
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 382, in format
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 748, in _translation_to_actions
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 812, in _atom_to_action
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 788, in _meta_to_action
  File "build/windist/data\Lib\site-packages\plover\registry.py", line 72, in get_plugin
KeyError: 'time'
2025-01-20 00:53:57,538 - INFO - Stroke(Z-DZ : ['Z-', '-D', '-Z'])
2025-01-20 00:53:57,539 - ERROR - Error in lookup function: 
2025-01-20 00:53:57,539 - ERROR - Error in lookup function: 
2025-01-20 00:53:57,540 - ERROR - engine on_stroked failed
Traceback (most recent call last):
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 147, in run
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 382, in _on_stroked
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 205, in translate
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 261, in flush
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 266, in _output
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 382, in format
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 748, in _translation_to_actions
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 812, in _atom_to_action
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 788, in _meta_to_action
  File "build/windist/data\Lib\site-packages\plover\registry.py", line 72, in get_plugin
KeyError: 'time'
2025-01-20 00:53:58,220 - INFO - Stroke(Z-Z : ['Z-', '-Z'])
2025-01-20 00:53:58,221 - ERROR - Error in lookup function: 
2025-01-20 00:53:58,221 - ERROR - Error in lookup function: 
2025-01-20 00:53:58,222 - ERROR - engine on_stroked failed
Traceback (most recent call last):
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 147, in run
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 382, in _on_stroked
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 205, in translate
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 261, in flush
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 266, in _output
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 382, in format
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 748, in _translation_to_actions
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 812, in _atom_to_action
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 788, in _meta_to_action
  File "build/windist/data\Lib\site-packages\plover\registry.py", line 72, in get_plugin
KeyError: 'time'
2025-01-20 00:54:01,344 - INFO - Stroke(Z-TZ : ['Z-', '-T', '-Z'])
2025-01-20 00:54:01,345 - ERROR - Error in lookup function: 
2025-01-20 00:54:01,345 - ERROR - Error in lookup function: 
2025-01-20 00:54:01,345 - ERROR - engine on_stroked failed
Traceback (most recent call last):
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 147, in run
  File "build/windist/data\Lib\site-packages\plover\engine.py", line 382, in _on_stroked
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 205, in translate
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 261, in flush
  File "build/windist/data\Lib\site-packages\plover\translation.py", line 266, in _output
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 382, in format
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 748, in _translation_to_actions
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 812, in _atom_to_action
  File "build/windist/data\Lib\site-packages\plover\formatting.py", line 788, in _meta_to_action
  File "build/windist/data\Lib\site-packages\plover\registry.py", line 72, in get_plugin
KeyError: 'time'
